### ISSUE TITLE
Better reporting for diffs

### ISSUE THREAD

**Issue by wclr** [purescript-spec/purescript-spec#116] opened 2021-05-14 12:47 UTC
Spec could have a better reporter for strings/arrays/objects equality check.

For example something like mocha does https://mochajs.org/#diffs (it uses [diff](https://github.com/kpdecker/jsdiff))
![image](https://user-images.githubusercontent.com/736697/118269623-6a0b6780-b4d8-11eb-9672-271ef5358cb8.png)

As for array, it could report at least at what index check fails, etc.

**Comment by owickstrom** [comment] 2021-05-16 15:16
Closing as duplicate of #51

**Closed by owickstrom** 2021-05-16 15:16 UTC
